# Generated by Django 5.0.1 on 2024-05-04 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regestered_as', models.CharField(choices=[('individual', 'Individual'), ('entity', 'entity')], max_length=30)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], max_length=30)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('education_level', models.CharField(choices=[('PhD', 'PhD'), ('MD', 'MD'), ('PhD_candinate', 'PhD_candinate'), ('masters', 'masters'), ('masters_student', 'masters_student'), ('bachelors', 'bachelors'), ('bachelor_student', 'bachelor_student'), ('other', 'other')], max_length=30)),
                ('science_ranking', models.CharField(choices=[('professor', 'professor'), ('assistant_professor', 'assistant_professor'), ('associated_professor', 'associated_professor'), ('other', 'other')], max_length=30)),
                ('mobile_phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be digits.', regex='^[0-9]*$')])),
                ('membership_type', models.CharField(choices=[('ordinary_author', 'ordinary_author'), ('student_author', 'student_author'), ('ut_student', 'ut_student'), ('ordinary_sutudent', 'ordinary_student'), ('free_participant', 'free_participant')], max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=200)),
                ('meal', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('attendance_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
            ],
        ),
    ]
