# Generated by Django 5.0.1 on 2024-05-06 12:11

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('holding_time', models.DateTimeField()),
                ('presenter', models.CharField(max_length=200)),
                ('about_presenter', models.TextField(blank=True, max_length=1000, null=True)),
                ('organizer', models.CharField(blank=True, max_length=200, null=True)),
                ('holding_place', models.TextField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('participants', models.ManyToManyField(blank=True, null=True, to='home.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_field', models.CharField(max_length=200)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.option')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.participant')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.survey')),
            ],
            options={
                'unique_together': {('participant', 'survey')},
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_text', models.TextField(max_length=1000)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.participant')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.survey')),
            ],
            options={
                'unique_together': {('participant', 'survey')},
            },
        ),
    ]
