# Generated by Django 5.0.1 on 2024-05-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_meeting_survey_option_selectedoption_opinion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='selectedoption',
            unique_together=set(),
        ),
    ]
