# Generated by Django 5.0.1 on 2024-05-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_selectedoption_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedOption',
            new_name='SelectOption',
        ),
    ]
