# Generated by Django 5.0.1 on 2024-05-14 11:33

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_selectedoption_selectoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='num',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(to='home.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='education_level',
            field=models.CharField(choices=[('phd', 'phd'), ('md', 'md'), ('phd_candinate', 'phd_candinate'), ('masters', 'masters'), ('masters_student', 'masters_student'), ('bachelors', 'bachelors'), ('bachelor_student', 'bachelor_student'), ('other', 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=home.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='regestered_as',
            field=models.CharField(choices=[('individual', 'individual'), ('entity', 'entity')], max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='title',
            field=models.CharField(choices=[('mr', 'mr'), ('mrs', 'mrs'), ('dr', 'dr')], max_length=30),
        ),
    ]
