# Generated by Django 5.0.1 on 2024-05-24 13:25

import django.core.validators
import functools
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_document_alter_participant_mobile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='option_field',
            new_name='option_text',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[functools.partial(home.models.validate_max_file_size, *(), **{'max_size': 10485760}), django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
