# Generated by Django 5.0.1 on 2024-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_option_field_option_option_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sending_attendance_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='survey_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sending_attendance_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='survey_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
