# Generated by Django 5.0.1 on 2024-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_event_sending_attendance_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sending_attendance_email',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sending_attendance_email',
            field=models.BooleanField(),
        ),
    ]
