# Generated by Django 5.0.1 on 2024-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_emaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sending_attendance_email',
        ),
        migrations.AddField(
            model_name='event',
            name='sending_attendansend_surveysce_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sending_attendance_email',
            field=models.BooleanField(default=True),
        ),
    ]
