# Generated by Django 5.0.1 on 2024-05-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_event_sending_attendance_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sending_attendansend_surveysce_email',
            new_name='sending_attendance_email',
        ),
    ]
