# Generated by Django 5.0.1 on 2024-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_event_sending_attendance_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='membership_type',
            field=models.CharField(choices=[('ordinary_author', 'ordinary_author'), ('student_author', 'student_author'), ('ut_student', 'ut_student'), ('ordinary_student', 'ordinary_student'), ('free_participant', 'free_participant')], max_length=30),
        ),
    ]
